#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export DEV_DSK=`host aavance.aka.corp.amazon.com | grep alias | awk 'NF>1{print substr($NF,1,length($NF)-1)}'`

#export ZSH_THEME_TIME_UPDATE_ENABLED=false

autoload colors && colors
autoload -Uz promptinit
promptinit
prompt time
